### ISSUE TITLE
Deploy multiple python3 flavors

### ISSUE THREAD

**Issue by bnavigator** [openSUSE/python-rpm-macros#66]
This is intended as a tracker issue for the introduction of multiple python3 flavors and better reference in changelogs. The python-rpm-macros package with enabled flavors of python36 and python38 is in [Staging:N](https://build.opensuse.org/project/show/openSUSE:Factory:Staging:N) and as expected various packages fail.

- related PRs: #64, #65, #67, #70, #71
- [Trello card](https://trello.com/c/hrSxAWjp/17-python3-coinstall)
- [Mailinglist thread](https://lists.opensuse.org/archives/list/packaging@lists.opensuse.org/thread/IRZ5Q5H3Z3BLQO7CHTYQRTOFIS6BFTQC) with some hints what to look out for.

**Comment by bnavigator** [comment]
- [ ] python-six: https://github.com/openSUSE/python-rpm-macros/pull/64#issuecomment-715373348 [sr#843620](https://build.opensuse.org/request/show/843620) (currently Staging:I)

**Comment by bnavigator** [comment]
- [ ] python-sip: [sr#843659](https://build.opensuse.org/request/show/843659)

**Comment by bnavigator** [comment]
- [ ] libxml2:python

**Comment by bnavigator** [comment]
- [ ] python-semanage -- the enhanced `%python_expand` macro (#64) does not like to substitute `"$python"` with the executable becuase of the `"`. Fix in specfile or in macro?

**Comment by bnavigator** [comment]
`%python3_only`

- [ ] [python-pytest](https://build.opensuse.org/package/show/home:bnavigator:branches:openSUSE:Factory:Staging:N/python-pytest) (on my branch of Staging:N) [sr#844489](https://build.opensuse.org/request/show/844489)

**Comment by bnavigator** [comment]
`BuildRequires: python3-foo`

[ ] [python-iniparse](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-iniparse) [sr#844934](https://build.opensuse.org/request/show/844934)

**Comment by mcepl** [comment]
%python_exec is broken with multiple python3 flavours #72

**Comment by bnavigator** [comment]
#70 already fixes that

**Comment by bnavigator** [comment]
Wrong shebang replacement

- [ ] [python-psutil](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-psutil)

**Comment by bnavigator** [comment]
Conflicting files outside of `%python_site(lib|arch)`

- [ ] [python-tqdm](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-tqdm)

**Comment by mcepl** [comment]
> Conflicting files outside of `%python_site(lib|arch)`
> 
>     * [ ]  [python-tqdm](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-tqdm)

I think this clearly calls for alternatives, however (and I guess Sphinx as well).

**Comment by scarabeusiv** [comment]
Why not just split bash completion file into subpkg, that would be the most proper solution.

**Comment by bnavigator** [comment]
I found a way that works with the old and new python_expand: [sr#845689](https://build.opensuse.org/request/show/845689)

**Comment by mcepl** [comment]
> I found a way that works with the old and new python_expand: [sr#845689](https://build.opensuse.org/request/show/845689)

??? This is not python-tqdm. ???

**Comment by bnavigator** [comment]
No it is psutil. Granted the history of https://github.com/openSUSE/python-rpm-macros/issues/66#issuecomment-721016747 makes it confusing :)

tqdm is in the making.

**Comment by bnavigator** [comment]
python-tqdm-bash-completion: Approach for the `Supplements:` tag in [sr#845737](https://build.opensuse.org/request/show/845737) is a bit hacky. Maybe we need to enhance %python_module or create a new macro for this kind of dependency specification.

**Comment by bnavigator** [comment]
> (and I guess Sphinx as well).

python-Sphinx is a case of #5.

**Comment by bnavigator** [comment]
duplicate files found by `%find_lang`
- [ ] [python-Sphinx](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-Sphinx) -- [sr#845821](https://build.opensuse.org/request/show/845821) -> [sr#845822](https://build.opensuse.org/request/show/845822) 
- [ ] [python-Sphinx2](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-Sphinx2) -- [sr#845824](https://build.opensuse.org/request/show/845824)

**Comment by bnavigator** [comment]
- [ ] many packages unresolvable because they look for python3-dateutil -- #77

**Comment by bnavigator** [comment]
Duh, the new python-sip had a wrong  files section header.

- [ ] [python-sip](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-sip) -- [sr#848979](https://build.opensuse.org/request/show/848979)

**Comment by bnavigator** [comment]
- [ ] python36-importlib-metadata is missing. Python38 provides it in -base, but python36 does need the extra package already provided in SLE and Leap.

**Comment by bnavigator** [comment]
After providing python36-importlib-metadata, pytest is usable. Some pytest runs in my branched staging:N failed because they found tests in `_build.python36` --> #78

**Comment by bnavigator** [comment]
Additional provides of python3-othername is not enough:

- [ ] [python-pycups provides python3-cups](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-pycups) -- [sr#849822](https://build.opensuse.org/request/show/849822)

**Comment by bnavigator** [comment]
Incorrect expansion of `$python` in `%python_expand`

- [ ] [python-dbus-python](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-dbus-python) -- [sr#849987](https://build.opensuse.org/request/show/849987)

**Comment by mcepl** [comment]
> Incorrect expansion of `$python` in `%python_expand`

Could you please elaborate on what’s wrong? Is the linked SR trying to fix the problem or is it a reproducer?

**Comment by bnavigator** [comment]
> > Incorrect expansion of `$python` in `%python_expand`
> 
> Could you please elaborate on what’s wrong? Is the linked SR trying to fix the problem or is it a reproducer?

It is trying to fix the problem. Without it `%configure PYTHON="/usr/bin/$python"` expands to `/usr/bin/usr/bin/python3.8`

**Comment by mcepl** [comment]
> It is trying to fix the problem. Without it `%configure PYTHON="/usr/bin/$python"` expands to `/usr/bin/usr/bin/python3.8`

And how many Spec files sets `$PYTHON`? Wouldn’t it be easier just to change them to `%configure PYTHON="$python"` and be done with it?

**Comment by bnavigator** [comment]
IIRC I did not test it. But my assumption was that there is a reason the variable for `%configure` needs to specify the absolute filepath. Until the update for python-rpm-macros will make it out of Staging:N, `$python` is replaced to `python3` without the bindir. `$(which $python)` will always return the correct absolute path, before and after the update.

**Comment by mcepl** [comment]
> IIRC I did not test it. But my assumption was that there is a reason the
> variable for `%configure` needs to specify the absolute filepath. Until the
> update for python-rpm-macros will make it out of Staging:N, `$python` is
> replaced to `python3` without the bindir. `$(which $python)` will always
> return the correct absolute path, before and after the update.

I see `$PYTHON` used only in contexts like ``PYTHON_SITE_PKG=`$PYTHON -c "import distutils.sysconfig; print (distutils.sysconfig.get_python_lib(0,0));"``` and then full path to the binary should work just fine.

**Comment by bnavigator** [comment]
full path or basename depending on correct $PATH?

**Comment by bnavigator** [comment]
> I see two: `python-dbus-python` and `gtk-doc`.

`gtk-doc` does not use `%python_expand`. No problem there.

**Comment by bnavigator** [comment]
With `%configure PYTHON="$python"`:

```
[   32s] + ../configure --host=x86_64-suse-linux-gnu --build=x86_64-suse-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-dependency-tracking PYTHON=python3
...
[   36s] checking for python... no
[   36s] configure: error: Cannot find python in your system path
[   36s] error: Bad exit status from /var/tmp/rpm-tmp.wWaBES (%build)
[   36s] 
```

**Comment by mcepl** [comment]
OK, so you are right. Just why to both set up the environmental variable `$PYTHON` and do it once more on `%configure` command line?

**Comment by bnavigator** [comment]
I don't know. It was introduced here: https://build.opensuse.org/request/show/620627. @scarabeusiv maybe just forgot to remove the export?

**Comment by bnavigator** [comment]
python-dbus-python SR updated: https://build.opensuse.org/request/show/850243

**Comment by mcepl** [comment]
> python-dbus-python SR updated: https://build.opensuse.org/request/show/850243

Oh, damn. I cannot approve that submit request.

**Comment by bnavigator** [comment]
Let's see if a maintainer from the Base:System project is willing to. This is not urgent.

**Comment by mcepl** [comment]
> Let's see if a maintainer from the Base:System project is willing to. This is not urgent.

Well, not urgent, but not whatever … Staging:N won’t be let through without it.

**Comment by bnavigator** [comment]
Yeah but there will be enough other packages to fix until this is the last blocker. I don't see it being let through anytime soon.

**Comment by bnavigator** [comment]
- [ ] [python-numpy](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-numpy)
  has a weird pytest call with wrong sitearch expansion and a conflicting f2py3 entry-point

**Comment by bnavigator** [comment]
pytest called without macro and thus importing from non-ignored _build directory with wrong flavor
- [ ] [python-async_generator](https://build.opensuse.org/package/show/devel:languages:python/python-async_generator) -- [sr#852715](https://build.opensuse.org/request/show/852715)

**Comment by bnavigator** [comment]
Requires python > 3.6

- [ ] [python-ipython](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-ipython) with conflicting ipython3 and iptest3 (when python39 will be there) -- [sr#852728]https://build.opensuse.org/request/show/852728)
- [ ] python-ipykernel (how to deal with jupyter in general??)

**Comment by bnavigator** [comment]
replace `%py3_compile` with `python_compileall`

- [ ] [python-jaraco.functools](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-jaraco.functools) -- [sr#852726](https://build.opensuse.org/request/show/852726) --> [sr#852727](https://build.opensuse.org/request/show/852727)

**Comment by bnavigator** [comment]
missing `%python_expand`

- [ ] [python-scikit-build](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-scikit-build) -- [sr#852764](https://build.opensuse.org/request/show/852764)

**Comment by bnavigator** [comment]
- [ ] [python-pyxdg](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-pyxdg) The `%python_exec .. $python/` did not expand correctly (/ not added in #67), but a version bump made the whole construct obsolete anyway-- [sr#852787](https://build.opensuse.org/request/show/852787)

**Comment by bnavigator** [comment]
Failures in python 3.6 build



- [ ] [python-aiohttp](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-aiohttp) -- [sr#853108](https://build.opensuse.org/request/show/853108) --> [sr#853123](https://build.opensuse.org/request/show/853123)

**Comment by bnavigator** [comment]
Use of python3 flavor

- [ ] [python-manuel](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-manuel) -- [sr#853004](https://build.opensuse.org/request/show/853005) --> [sr#853080](https://build.opensuse.org/request/show/853080)

**Comment by bnavigator** [comment]
Fix by update or removal of unnecessary BuildRequirements

- [ ] [python-setproctitle](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-setproctitle) -- [sr#853003](https://build.opensuse.org/request/show/853003) --> [sr#853085](https://build.opensuse.org/request/show/853085)
- [ ] [python-gunicorn](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-gunicorn) -- [sr#853088](https://build.opensuse.org/request/show/853088) --> [sr#853097](https://build.opensuse.org/request/show/853097)

**Comment by bnavigator** [comment]
Requires python > 3.6

- [ ] [python-curio](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-curio) -- [sr#852974](https://build.opensuse.org/request/show/852974) --> [sr#853082](https://build.opensuse.org/request/show/853082) 
  Upstream reverted back to python >= 3.6 for the current version, but the unit tests fail: dabeaz/curio#336. We might need to fix this because the dependency tree is huge:
  - [ ] [python-sniffio](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-sniffio) -- [sr#853087](https://build.opensuse.org/request/show/853087) --> [sr#853098](https://build.opensuse.org/request/show/853098)
  - [ ] [python-trio](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-trio) 
  - [ ] [python-dnspython](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-dnspython)

**Comment by bnavigator** [comment]
Missing dependency to libsqlite now:

- [ ] [breezy](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/breezy)

**Comment by bnavigator** [comment]
- [ ] [python-black](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-black) needs dataclasses.
  - [ ] python-dataclasses is provided by python stdlib >= 3.7. The python36 flavor will need the PyPI package, which needs python36-setuptools. Can we get [this](https://build.opensuse.org/package/show/home:bnavigator:branches:openSUSE:Factory:Staging:N/python36-dataclasses) directly as a new package into Staging:N?

**Comment by mcepl** [comment]
>     * [ ]  [python-black](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-black) needs dataclasses.-- [sr#853335](https://build.opensuse.org/request/show/853335)
>       
>       * [ ]  python-dataclasses is provided by python stdlib >= 3.7. The python36 flavor will need the PyPI package, which needs python36-setuptools. Can we get [this](https://build.opensuse.org/package/show/home:bnavigator:branches:openSUSE:Factory:Staging:N/python36-dataclasses) directly as a new package into Staging:N?

Sure thing. Submit it to Factory and ask `DimStar` on `#opensuse-python` on Freenode to put it into :N (or tell me, and I will communicate it with him).

**Comment by bnavigator** [comment]
> Sure thing. Submit it to Factory and ask @DimStar77 (`DimStar` in `#opensuse-python` on Freenode) to put it into :N (or tell me, and I will communicate it with him).

Submit directly form ~:branches to Factory or through d:l:p?

**Comment by mcepl** [comment]
> Submit directly from ~:branches to Factory or through d:l:p?

Sorry, I was not clear. Through d:l:p, of course. We want to keep it maintained, don’t we?

**Comment by bnavigator** [comment]
> Sorry, I was not clear. Through d:l:p, of course. We want to keep it maintained, don’t we?

[python36-dataclasses sr#853381](https://build.opensuse.org/request/show/853381). Please tell @DimStar77 as soon as you accept and forward to Factory - if he doesn't read his GitHub notifications.

**Comment by bnavigator** [comment]
We are also at a point where we need `Prefer: python36-foo python38-foo` in the prjconf instead of `Prefer: python3-foo` (or the negative `-python36-foobar` equivalent), e.g. for
- pytest
- Sphinx
- tornado

**Comment by bnavigator** [comment]
python-curses no longer in a standard dependency chain.

- [ ] [python-tornado5](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-tornado5) -- [sr#853429](https://build.opensuse.org/request/show/853429)

This was quite hard to debug. How do you get from
```
[   31s] + /usr/bin/python3.6 -Bm tornado.test.runtests
[   32s] Exception ignored in: <_io.FileIO name='/usr/lib64/python3.6/_import_failed/import_failed.map' mode='rb' closefd=True>
[   32s] ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/lib64/python3.6/_import_failed/import_failed.map' mode='r' encoding='UTF-8'>
```

to finding out what failed to import? I ended up adding a `print()` statement to `/usr/lib64/python3.6/_import_failed/import_failed.py` to find out, `curses` could not be imported. Still don't know the import call.

**Comment by bnavigator** [comment]
## breezy

> I am working on this, but it is BS … nobody should ever need `pysqlite2` ever (when `sqlite3` is in the standard library). I will need to investigate it more on Monday. -- @mcepl

That's actually the solution! The standard library was missing! The import_failed.map from the tornado5 fix gave me that idea.
--> [sr#853438](https://build.opensuse.org/request/show/853438) to your branch. Not sure though, where the automatic pull in of the full python3 package got lost and whether we need to fix that.

**Comment by bnavigator** [comment]
> Requires python > 3.6
> 
> * [ ]  [python-ipython](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-ipython)

This will either
 * require to introduce skip_python36 for all packages depending on ipython, which is quite a lot.
 * Something like [python-ipython715](https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:jupyter/python-ipython715) or LTS python-ipython5 with the appropriate `Prefer:` lines introduced into the prjconfs. It would also help with Leap :backports.

**Comment by bnavigator** [comment]
The packages with [Cloud:OpensStack:Factory](https://build.opensuse.org/project/show/Cloud:OpenStack:Factory) will need special treatment. Ping @dirkmueller 

e.g.
- [ ] [python-cliff](https://build.opensuse.org/package/show/openSUSE:Factory:Staging:N/python-cliff) produces only python3-cliff but we need python36-cliff and python38-cliff, the latter providing python3-cliff

**Comment by mcepl** [comment]
> The packages with [Cloud:OpensStack:Factory](https://build.opensuse.org/project/show/Cloud:OpenStack:Factory) will need special treatment. Ping @dirkmueller

General advice around OpenStack stuff … unless you have to (i.e., some non-OpenStack package depends on it) you don’t touch it. Their build system is weird. Moreover, with the end of OpenStack efforts in SUSE, it is quite likely that the whole thing will go anyway.

**Comment by bnavigator** [comment]
Then we have to change all non-OpenStack packages depending on packages coming from there to BuildRequire python3- packages, and only provide them for the primary interpreter. Possible.

**Comment by mcepl** [comment]
@bnavigator Do we have some SOP for making packages python36-only? E.g., https://build.opensuse.org/package/show/openSUSE:Factory/python-typing_extensions

**Comment by bnavigator** [comment]
Several options
- no singlespec at all like https://build.opensuse.org/package/show/devel:languages:python/python36-dataclasses
- Redefine `%pythons`
  ```spec
  %if 0%{?python3_version_nodots} <= 36
  %define pythons python3
  %else
  %define pythons python36
  %endif
  ```
  I am not sure if this works with the OBS resolver, probably need to make it conditional on `%suse_version` rather than `%python3_version_nodots`
- Skip all unwanted flavors similar as above

**Comment by mcepl** [comment]
>     * no singlespec at all like https://build.opensuse.org/package/show/devel:languages:python/python36-dataclasses

Any comments on https://build.opensuse.org/request/show/862392 ?

**Comment by bnavigator** [comment]
Left a comment.

Be sure to check naming and provides/obsoletes conflicts with SLE/Leap packages in backports and :Update.

**Comment by bnavigator** [comment]
I thought we were slowly converging, but approaching zero seems hard. Currently fixing build dependency cycles.

- [ ] python-typing_extensions pulled full python through -testing
- [ ] python-gobject must exclude libgtk3 for all flavors.

**Comment by bnavigator** [comment]
- [x] python-libcst:test fails on i586 (skipping test now) https://github.com/Instagram/LibCST/issues/442

**Comment by bnavigator** [comment]
Brace yourselves. Staging:N is green.

**Comment by mcepl** [comment]
Is there anything to do here, or should we close it already?

**Comment by bnavigator** [comment]
It's not merged into Factory yet. But I think this issue has served its purpose.
